### ISSUE TITLE
Music playback does not work correctly, whatsoever

### ISSUE THREAD

**Issue by IAGOnDiscord** [Mcharlsto/rat#2]
The `audio.opus` file does not play when running the `rat` executable. Executing `script.sh` does play `audio.opus` as expected, but a bar appears below the rat to indicate progress.
The former issue plagues the AUR package, as the `rat` executable is what is being executed.

**Comment by Mcharlsto** [comment]
Hi. Done some testing and it turns out this is another dependency issue, extracting binary files (like audio.opus) depends on the `uudecode` command from `sharutils`, so the file just isn't being created. This is what I get for forgetting to test on a clean machine...

**Comment by Mcharlsto** [comment]
Fixed over on the AUR with `1.0.2`.

**Comment by IAGOnDiscord** [comment]
I tested this afternoon, and audio playback seems to still be problematic in both `script.sh` and the `rat` binary. Same issues as prior. Will begin work on a PR to try and fix.
