### ISSUE TITLE
REQUEST: Rust port

### ISSUE THREAD

**Issue by IAGOnDiscord** [Mcharlsto/rat#8]
I want to make a Rust port of `horizontallyspinningrat` that introduces additional features and employs ncurses to cut back on flashing. Before I set out to write it though, I would like your permission, as I don't want to infringe on this project.

**Comment by Mcharlsto** [comment]
Sure, go for it. I wrote this as a quick joke in a couple of hours, so the code is about as hacky as it gets, there's a lot of room for improvement. Let me know how you get on.

**Comment by IAGOnDiscord** [comment]
Thanks!

**Comment by NotAShelf** [comment]
https://github.com/yavko/rat-rs guys it's memory safe

**Comment by thinkingsand** [comment]
Haha, nice. Someone finally did it. 
I was going to but learning rust just for this felt really stupid - hence the janky C version.
